"""Add softdeleted column

Revision ID: 1abf923779cd
Revises: b0a34aba30d8
Create Date: 2025-09-29 16:41:31.128335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abf923779cd'
down_revision: Union[str, Sequence[str], None] = 'b0a34aba30d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('softdeleted', sa.Integer(), nullable=True))
    op.add_column('Loan', sa.Column('softdeleted', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('softdeleted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'softdeleted')
    op.drop_column('Loan', 'softdeleted')
    op.drop_column('Books', 'softdeleted')
    # ### end Alembic commands ###
