"""Add BookAvl,Membership,softdeleted column

Revision ID: 91bec26bc808
Revises: 1abf923779cd
Create Date: 2025-09-29 16:48:44.610647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bec26bc808'
down_revision: Union[str, Sequence[str], None] = '1abf923779cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('BookAvl', sa.Integer(), nullable=True))
    op.drop_column('Books', 'softdeleted')
    op.add_column('Loan', sa.Column('Softdelete', sa.Integer(), nullable=True))
    op.drop_column('Loan', 'softdeleted')
    op.add_column('Users', sa.Column('Membership', sa.Integer(), nullable=True))
    op.drop_column('Users', 'softdeleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('softdeleted', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'Membership')
    op.add_column('Loan', sa.Column('softdeleted', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Loan', 'Softdelete')
    op.add_column('Books', sa.Column('softdeleted', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Books', 'BookAvl')
    # ### end Alembic commands ###
