"""Add BookAvl,Membership,softdeleted column

Revision ID: d28ed7047ad2
Revises: 91bec26bc808
Create Date: 2025-09-30 11:35:26.293940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28ed7047ad2'
down_revision: Union[str, Sequence[str], None] = '91bec26bc808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
